name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "No tests yet" # Replace with `npm test` if you have tests

    - name: Build Docker image
      run: docker build -t node-app .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH }}
        script: |
          docker stop node-app || true
          docker rm node-app || true
          docker rmi node-app || true
          cd ~/app || mkdir ~/app && cd ~/app
          rm -rf *
          git clone https://github.com/akshu-r/CI-CD-pipeline-Node-JS.git .
          docker build -t node-app .
          docker run -d -p 3000:3000 --name node-app node-app

